micronaut:
    application:
        name: micronaut_rest
    server:
        cors: 
            enabled: true

datasources:
    default:
        url: jdbc:mariadb://localhost:3307/db_micronaut_rest
        username: root
        password: "password"
        driverClassName: org.mariadb.jdbc.Driver 
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update